export const GET_USER_ING = 'GET_USER_ING';
export const GET_USER_SUCCESS = 'GET_USERPIN_SUCCESS';
export const GET_USER_FAIL = 'GET_USERPIN_FAIL';
export const SET_USER = 'SET_USER';
export const GET_POSITION_SUCCESS = 'GET_POSITION_SUCCESS';
export const GET_POSITION_ERRROR = 'GET_POSITION_ERROR';

export const GET_POST_ING = 'GET_POST_ING';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_FAIL = 'GET_POST_FAIL';

export const GET_PET_ING = 'GET_PET_ING';
export const GET_PET_SUCCESS = 'GET_PET_SUCCESS';
export const GET_PET_FAIL = 'GET_PET_FAIL';
